Summary:
find_next: error for input x=0: Output argument "y" (and maybe others) not assigned during call to "find_next".
findq: input a=5 n=4 tol=1e-09 maxit=10000: Output argument "q" (and maybe others) not assigned during call to "findq".

 Complete output:

find_next: error for input x=0: Output argument "y" (and maybe others) not assigned during call to "find_next".

findq: input a=5 n=4 tol=1e-09 maxit=10000: Output argument "q" (and maybe others) not assigned during call to "findq".
